### ISSUE TITLE
Doesn't run in Safari

### ISSUE THREAD

**Issue by JoshDoug** [wizgrav/clubber#4]
In case you're unaware, http://wizgrav.github.io/clubber doesn't run in Safari (or Safari TP, or WebKit Nightly).

Web Inspector Console shows the following issues:

[Error] IndexSizeError (DOM Exception 1): The index is not in the allowed range.
	Clubber (clubber.js:57)
	Global Code (common.js:19)

[Error] TypeError: undefined is not an object (evaluating 'clubber.smoothing = [0.66, 0.8, 0.92][id]')
	threshold (main.js:16)
	Global Code (main.js:60)

**Comment by wizgrav** [comment]
Thanks, I was indeed unaware. It seems that requesting 4096 samples for the FFT may be too much for webkit. I put it down to 2048, I think this should fix it. Please test and tell so we can close this.

**Comment by JoshDoug** [comment]
That has fixed it, although the performance is quite poor compared to Chrome.
Looks good to close though.
