### ISSUE TITLE
mobile / other browser comptibility

### ISSUE THREAD

**Issue by MacroMachines** [wizgrav/clubber#7]
reference Meyda audio feature extraction library, somehow they managed to make it work on mobile and barely compatible browsers.  https://github.com/meyda/meyda

**Comment by MacroMachines** [comment]
they use the script processor node : https://medias.ircam.fr/x8fbaf8

**Comment by wizgrav** [comment]
Correct me if I misunderstood, I recently integrated clubber for a client using an offline webaudio context and the script processor. The only thing one needs to do in this case is passing the appropriate time in clubber. Eg if the processor consumes 256 samples at a time and the context is 44.1 Khz the call should be clubber.update(256/44.1). Other than that the offline context could be passed to clubber to create the analyzer inside it but you can also pass the frequency data manually as the second argument to clubber.update(), no need to listen() any element in this case

**Comment by wizgrav** [comment]
Closing this as the script processor node is supported
